### PR TITLE
72 check valid venmo paypal links

### PR DESCRIPTION
**Pull request by brooklynbagel**
Opening the PR but it's not necessarily ready for merge yet. There may need to be a few iterations before it's ready to be brought into master, but this is to get the ball rolling. In response to issue #72

### CODE REVIEW

**Comment by brooklynbagel** [comment]
An alternative method to one big test function is to write one for each payment provider (Venmo, Paypal, etc), for example one for Venmo might look like

```js
// other steps in validation go here
.test('valid-venmo-link', 'need a valid Venmo link', function(value) {
  if (!value) return false;
  let hostname = value.split('/')[2];
  if (hostname !== 'venmo.com') return false;
  let path = value.split('/')[3];
  return /^code\?user_id=[0-9]{19}$/.test(path);
})
// other steps in validation go here
```

**Comment by brooklynbagel** [comment]
Can you give some examples of the proper PayPal links? Right now it's not checking for the www subdomain but paypal.me should be okay  I'm curious which test cases work and which test cases don't work

**Comment by samyoungnyc** [comment]
Here are some of the links that don't work correctly:

SHOULD WORK -> www.venmo.com/code?user_id=1882421972697088249 ⛔️
SHOULD WORK -> https://paypal.me/jordandavidartistry ✅
SHOULD WORK -> https://www.paypal.me/tomoyaforster ⛔️

I think for Paypal - if **https://www**.paypal.me/xxx is attached you should allow it.

If **www** does NOT append to **https://** (i.e www.paypal.me/xxx), you shouldn't and it doesn't allow it (nothing you need to do for this case)

DOES WORK -> https://paypal.me/jordandavidartistry ✅

SHOULD NOT WORK -> www.paypal.me/jordandavidartistry ✅

**Comment by brooklynbagel** [comment]
Modified to merge into branch staging

**Pull request merged**
